import { Check, Copy, Sparkles } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { participants } from '../../data/mockData'
import type { Meeting, MeetingWorkspaceData, WorkspaceActionItem } from '../../types'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'

interface MeetingSummaryProps {
  actionItems: WorkspaceActionItem[]
  meeting: Meeting
  workspace: MeetingWorkspaceData
}

export function MeetingSummary({ actionItems, meeting, workspace }: MeetingSummaryProps) {
  const [copied, setCopied] = useState(false)

  if (!workspace.hasSummary) {
    return (
      <Card className="p-8 text-center">
        <Sparkles className="mx-auto text-muted" size={24} />
        <h3 className="mt-3 text-lg font-semibold text-foreground">Summary unavailable</h3>
        <p className="mx-auto mt-2 max-w-md text-sm leading-6 text-secondary">
          {meeting.aiStatus === 'Processing'
            ? 'A sample summary is still processing for this meeting.'
            : 'This meeting does not have a sample AI summary yet.'}
        </p>
      </Card>
    )
  }

  const copySummary = async () => {
    const lines = [
      `Meeting: ${meeting.title}`,
      '',
      'Executive Summary',
      workspace.executiveSummary ?? workspace.summary ?? '',
      '',
      'Key Topics',
      ...workspace.keyTopics.map((topic) => `• ${topic}`),
      '',
      'Key Decisions',
      ...workspace.keyDecisions.map((item) => `• ${item}`),
      '',
      'Action Items',
      ...actionItems.map((item) => {
        const assignee = participants.find((participant) => participant.id === item.assigneeId)?.name ?? 'Unassigned'
        return `• ${item.task} — ${assignee}${item.dueDate ? ` (${item.dueDate})` : ''} [${item.status}]`
      }),
      '',
      'Unresolved Questions',
      ...workspace.unresolvedQuestions.map((item) => `• ${item}`),
      '',
      'Next Steps',
      ...workspace.nextSteps.map((item) => `• ${item}`),
      '',
      'Note: Sample summary for frontend demonstration — not generated by a live AI model.',
    ]

    try {
      await navigator.clipboard.writeText(lines.join('\n'))
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      setCopied(false)
    }
  }

  return (
    <div className="grid gap-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="text-lg font-semibold text-foreground">Meeting Summary</h3>
          <p className="mt-1 text-sm text-muted">Sample content for demonstration · not a live model output</p>
        </div>
        <Button onClick={copySummary} type="button" variant="secondary">
          {copied ? <Check size={16} /> : <Copy size={16} />}
          {copied ? 'Copied' : 'Copy Summary'}
        </Button>
      </div>

      <SummarySection title="Executive Summary">
        <p className="text-sm leading-6 text-secondary">{workspace.executiveSummary ?? workspace.summary}</p>
      </SummarySection>

      <SummarySection title="Key Topics">
        <div className="flex flex-wrap gap-2">
          {workspace.keyTopics.map((topic) => (
            <span className="rounded-md border border-border bg-subtle px-2.5 py-1 text-xs font-medium text-secondary" key={topic}>{topic}</span>
          ))}
        </div>
      </SummarySection>

      <SummarySection title="Key Decisions">
        <BulletList items={workspace.keyDecisions} empty="No decisions recorded." />
      </SummarySection>

      <SummarySection title="Action Items">
        {actionItems.length === 0 ? (
          <p className="text-sm text-muted">No action items recorded.</p>
        ) : (
          <ul className="grid gap-2">
            {actionItems.map((item) => {
              const assignee = participants.find((participant) => participant.id === item.assigneeId)?.name ?? 'Unassigned'
              return (
                <li className="rounded-md border border-border px-3 py-2.5 text-sm text-secondary" key={item.id}>
                  <span className="font-medium text-foreground">{item.task}</span>
                  <span className="mt-1 block text-xs text-muted">{assignee}{item.dueDate ? ` · ${item.dueDate}` : ''} · {item.status}</span>
                </li>
              )
            })}
          </ul>
        )}
      </SummarySection>

      <SummarySection title="Unresolved Questions">
        <BulletList items={workspace.unresolvedQuestions} empty="No unresolved questions." />
      </SummarySection>

      <SummarySection title="Next Steps">
        <BulletList items={workspace.nextSteps} empty="No next steps recorded." />
      </SummarySection>
    </div>
  )
}

function SummarySection({ children, title }: { children: ReactNode; title: string }) {
  return (
    <Card className="p-5">
      <h4 className="text-sm font-semibold text-foreground">{title}</h4>
      <div className="mt-3">{children}</div>
    </Card>
  )
}

function BulletList({ empty, items }: { empty: string; items: string[] }) {
  if (items.length === 0) return <p className="text-sm text-muted">{empty}</p>
  return (
    <ul className="grid gap-2">
      {items.map((item) => (
        <li className="rounded-md border border-border bg-subtle/40 px-3 py-2.5 text-sm leading-6 text-secondary" key={item}>{item}</li>
      ))}
    </ul>
  )
}
