import { CheckSquare, CircleHelp, ListTree, Sparkles, Users } from 'lucide-react'
import { participants } from '../../data/mockData'
import type { Meeting, MeetingWorkspaceData, MeetingWorkspaceTab, QAChatMessage, WorkspaceActionItem } from '../../types'
import { AiBadge } from '../meetings/MeetingCard'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'
import { MeetingQAChat } from './MeetingQAChat'

interface MeetingOverviewProps {
  actionItems: WorkspaceActionItem[]
  meeting: Meeting
  messages: QAChatMessage[]
  onMessagesChange: (messages: QAChatMessage[]) => void
  onOpenTab: (tab: MeetingWorkspaceTab) => void
  workspace: MeetingWorkspaceData
}

export function MeetingOverview({ actionItems, meeting, messages, onMessagesChange, onOpenTab, workspace }: MeetingOverviewProps) {
  const previewItems = actionItems.slice(0, 3)
  const meetingParticipants = workspace.participantDetails.map((detail) => {
    const person = participants.find((participant) => participant.id === detail.participantId)
    return person ? { ...person, role: detail.role } : null
  }).filter(Boolean)

  return (
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,0.9fr)]">
      <div className="grid gap-5">
        <Card className="p-5">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <p className="inline-flex items-center gap-2 text-sm font-semibold text-foreground"><Sparkles className="text-ai" size={16} />AI Summary</p>
              <p className="mt-1 text-xs text-muted">Sample summary for demonstration · not generated by a live model</p>
            </div>
            <AiBadge status={meeting.aiStatus ?? 'No Transcript'} />
          </div>
          {workspace.hasSummary && workspace.summary ? (
            <>
              <p className="mt-4 text-sm leading-6 text-secondary">{workspace.summary}</p>
              <Button className="mt-4" onClick={() => onOpenTab('summary')} type="button" variant="secondary">View Full Summary</Button>
            </>
          ) : (
            <div className="mt-4 rounded-md border border-dashed border-border bg-subtle/60 px-4 py-6 text-sm text-secondary">
              {meeting.aiStatus === 'Processing'
                ? 'Summary is still processing for this meeting. Check back once generation finishes.'
                : 'No AI summary is available for this meeting yet.'}
            </div>
          )}
        </Card>

        <Card className="p-5">
          <h3 className="text-sm font-semibold text-foreground">Key Topics</h3>
          {workspace.keyTopics.length === 0 ? (
            <p className="mt-3 text-sm text-muted">No topics recorded for this meeting.</p>
          ) : (
            <div className="mt-3 flex flex-wrap gap-2">
              {workspace.keyTopics.map((topic) => <Badge key={topic}>{topic}</Badge>)}
            </div>
          )}
        </Card>

        <Card className="p-5">
          <h3 className="inline-flex items-center gap-2 text-sm font-semibold text-foreground"><ListTree size={16} className="text-muted" />Key Decisions</h3>
          {workspace.keyDecisions.length === 0 ? (
            <p className="mt-3 text-sm text-muted">No decisions have been recorded yet.</p>
          ) : (
            <ul className="mt-3 grid gap-2">
              {workspace.keyDecisions.map((decision) => (
                <li className="rounded-md border border-border bg-subtle/40 px-3 py-2.5 text-sm leading-6 text-secondary" key={decision}>{decision}</li>
              ))}
            </ul>
          )}
        </Card>

        <Card className="p-5">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h3 className="inline-flex items-center gap-2 text-sm font-semibold text-foreground"><CheckSquare size={16} className="text-muted" />Action Items Preview</h3>
            <Button onClick={() => onOpenTab('action-items')} size="sm" type="button" variant="ghost">View All Action Items</Button>
          </div>
          {previewItems.length === 0 ? (
            <p className="mt-3 text-sm text-muted">No action items for this meeting.</p>
          ) : (
            <ul className="mt-3 divide-y divide-border rounded-md border border-border">
              {previewItems.map((item) => {
                const assignee = participants.find((participant) => participant.id === item.assigneeId)
                return (
                  <li className="flex flex-wrap items-center justify-between gap-2 px-3 py-3" key={item.id}>
                    <div>
                      <p className="text-sm font-medium text-foreground">{item.task}</p>
                      <p className="mt-1 text-xs text-muted">{assignee?.name ?? 'Unassigned'}{item.dueDate ? ` · ${item.dueDate}` : ''}</p>
                    </div>
                    <Badge tone={item.status === 'completed' ? 'success' : 'info'}>{item.status === 'completed' ? 'Completed' : 'Open'}</Badge>
                  </li>
                )
              })}
            </ul>
          )}
        </Card>

        <Card className="p-5">
          <h3 className="inline-flex items-center gap-2 text-sm font-semibold text-foreground"><CircleHelp size={16} className="text-muted" />Unresolved Questions</h3>
          {workspace.unresolvedQuestions.length === 0 ? (
            <p className="mt-3 text-sm text-muted">No unresolved questions remain.</p>
          ) : (
            <ul className="mt-3 grid gap-2">
              {workspace.unresolvedQuestions.map((question) => (
                <li className="rounded-md border border-border px-3 py-2.5 text-sm leading-6 text-secondary" key={question}>{question}</li>
              ))}
            </ul>
          )}
        </Card>
      </div>

      <div className="grid gap-5 self-start">
        <MeetingQAChat meeting={meeting} messages={messages} onMessagesChange={onMessagesChange} workspace={workspace} />

        <Card className="p-5">
          <h3 className="inline-flex items-center gap-2 text-sm font-semibold text-foreground"><Users size={16} className="text-muted" />Participants</h3>
          <p className="mt-1 text-xs text-muted">{meetingParticipants.length} people in this meeting</p>
          <ul className="mt-3 grid gap-2">
            {meetingParticipants.map((person) => person && (
              <li className="flex items-start gap-3 rounded-md border border-border px-3 py-2.5" key={person.id}>
                <span className="grid size-8 shrink-0 place-items-center rounded-full bg-subtle text-xs font-semibold text-secondary">{person.initials}</span>
                <div className="min-w-0">
                  <p className="text-sm font-medium text-foreground">{person.name}</p>
                  <p className="mt-0.5 text-xs leading-5 text-muted">{person.role}</p>
                </div>
              </li>
            ))}
          </ul>
        </Card>

        <Card className="p-5">
          <h3 className="text-sm font-semibold text-foreground">Meeting Information</h3>
          <dl className="mt-3 grid gap-2 text-sm">
            <InfoRow label="Date" value={meeting.dateLabel} />
            <InfoRow label="Duration" value={meeting.duration} />
            <InfoRow label="Participants" value={String(meeting.participantIds.length)} />
            <InfoRow label="Status" value={meeting.status} />
            <InfoRow label="Transcript" value={workspace.hasTranscript ? 'Available' : 'Unavailable'} />
            <InfoRow label="AI summary" value={workspace.hasSummary ? 'Available' : (meeting.aiStatus ?? 'Unavailable')} />
          </dl>
        </Card>
      </div>
    </div>
  )
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-3 border-b border-border py-2 last:border-b-0">
      <dt className="text-muted">{label}</dt>
      <dd className="text-right font-medium capitalize text-foreground">{value}</dd>
    </div>
  )
}
