import { useState } from 'react'
import type { Meeting } from '../../types'
import { Button } from '../ui/Button'
import { Input } from '../ui/Input'
import { Modal } from '../ui/Modal'

interface CreateMeetingModalProps { initialMeeting?: Meeting | null; isOpen: boolean; onClose: () => void; onCreate: (meeting: Meeting) => void }

export function CreateMeetingModal({ initialMeeting = null, isOpen, onClose, onCreate }: CreateMeetingModalProps) {
  const [title, setTitle] = useState(initialMeeting?.title ?? ''); const [description, setDescription] = useState(initialMeeting?.description ?? ''); const [date, setDate] = useState(initialMeeting?.dateValue ?? ''); const [time, setTime] = useState(initialMeeting?.time ?? ''); const [duration, setDuration] = useState(initialMeeting?.duration ?? '45 min'); const [participants, setParticipants] = useState(initialMeeting?.participantIds.length ? 'Participants added' : ''); const [error, setError] = useState('')
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!title.trim() || !date || !time) { setError('Meeting title, date, and time are required.'); return }; const dateLabel = new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(new Date(`${date}T00:00:00`)); onCreate({ ...initialMeeting, id: initialMeeting?.id ?? `meeting-${Date.now()}`, title: title.trim(), description: description.trim(), dateLabel: `${dateLabel} · ${new Date(`2000-01-01T${time}`).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}`, dateValue: date, time, duration, participantIds: participants ? initialMeeting?.participantIds ?? ['sanika', 'rahul'] : ['sanika'], status: initialMeeting?.status ?? 'upcoming' }); setError('') }
  return <Modal isOpen={isOpen} onClose={onClose} title={initialMeeting ? 'Edit meeting' : 'Create meeting'}><form className="grid gap-4" onSubmit={submit}><Input label="Meeting title" onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Product architecture review" value={title} /><label className="grid gap-1.5 text-sm text-secondary"><span className="font-medium text-foreground">Description</span><textarea className="min-h-20 rounded-md border border-border bg-subtle px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted focus:border-accent" onChange={(event) => setDescription(event.target.value)} placeholder="Add context for participants" value={description} /></label><div className="grid gap-4 sm:grid-cols-2"><Input label="Date" onChange={(event) => setDate(event.target.value)} type="date" value={date} /><Input label="Time" onChange={(event) => setTime(event.target.value)} type="time" value={time} /></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm text-secondary"><span className="font-medium text-foreground">Expected duration</span><select className="h-10 rounded-md border border-border bg-subtle px-3 text-sm text-foreground outline-none focus:border-accent" onChange={(event) => setDuration(event.target.value)} value={duration}><option>30 min</option><option>45 min</option><option>60 min</option></select></label><Input label="Participants" onChange={(event) => setParticipants(event.target.value)} placeholder="Add names" value={participants} /></div>{error && <p className="text-sm text-danger" role="alert">{error}</p>}<div className="mt-1 flex justify-end gap-2"><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button type="submit">{initialMeeting ? 'Save changes' : 'Create Meeting'}</Button></div></form></Modal>
}
