import { CalendarDays, CheckSquare, Clock3, MoreHorizontal, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Meeting, Participant } from '../../types'
import { Badge } from '../ui/Badge'
import { Card } from '../ui/Card'

interface MeetingCardProps { meeting: Meeting; onArchive: (meeting: Meeting) => void; onDelete: (meeting: Meeting) => void; onEdit: (meeting: Meeting) => void; participants: Participant[] }

export function MeetingCard({ meeting, onArchive, onDelete, onEdit, participants }: MeetingCardProps) {
  const meetingParticipants = participants.filter((participant) => meeting.participantIds.includes(participant.id))
  return <Card className="group relative flex min-h-60 flex-col p-5 transition-colors hover:border-secondary/30"><div className="flex items-start gap-3"><Link className="min-w-0 flex-1" to={`/meetings/${meeting.id}`}><h2 className="truncate text-base font-semibold text-foreground hover:text-accent">{meeting.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-5 text-secondary">{meeting.description}</p></Link><MeetingActionsMenu meeting={meeting} onArchive={onArchive} onDelete={onDelete} onEdit={onEdit} /></div><div className="mt-5 grid gap-2 text-xs text-muted"><span className="inline-flex items-center gap-2"><CalendarDays size={14} />{meeting.dateLabel}</span><span className="inline-flex items-center gap-2"><Clock3 size={14} />{meeting.duration}</span></div><div className="mt-5 flex items-center justify-between gap-3"><div className="flex -space-x-1.5">{meetingParticipants.slice(0, 4).map((participant) => <span className="grid size-6 place-items-center rounded-full border-2 border-card bg-subtle text-[9px] font-semibold text-secondary" key={participant.id} title={participant.name}>{participant.initials}</span>)}</div><span className="inline-flex items-center gap-1 text-xs text-muted"><Users size={14} />{meeting.participantIds.length} participants</span></div><div className="mt-5 flex flex-wrap items-center gap-2"><StatusBadge status={meeting.status} /><AiBadge status={meeting.aiStatus ?? 'No Transcript'} /></div><div className="mt-auto flex items-center justify-between border-t border-border pt-4"><span className="inline-flex items-center gap-1.5 text-xs text-secondary"><CheckSquare size={14} />{meeting.actionItemCount ?? 0} action items</span><Link className="text-sm font-medium text-accent hover:text-[#4338ca]" to={`/meetings/${meeting.id}`}>View meeting</Link></div></Card>
}

export function MeetingActionsMenu({ meeting, onArchive, onDelete, onEdit }: Omit<MeetingCardProps, 'participants'>) { return <details className="relative"><summary aria-label="Meeting actions" className="list-none rounded-md p-1 text-muted hover:bg-subtle hover:text-foreground [&::-webkit-details-marker]:hidden"><MoreHorizontal size={19} /></summary><div className="absolute right-0 z-20 mt-1 w-32 rounded-md border border-border bg-card p-1 shadow-floating"><Link className="block rounded-sm px-2.5 py-2 text-sm text-secondary hover:bg-subtle hover:text-foreground" to={`/meetings/${meeting.id}`}>View</Link><button className="block w-full rounded-sm px-2.5 py-2 text-left text-sm text-secondary hover:bg-subtle hover:text-foreground" onClick={() => onEdit(meeting)} type="button">Edit</button><button className="block w-full rounded-sm px-2.5 py-2 text-left text-sm text-secondary hover:bg-subtle hover:text-foreground" onClick={() => onArchive(meeting)} type="button">{meeting.status === 'archived' ? 'Restore' : 'Archive'}</button><button className="block w-full rounded-sm px-2.5 py-2 text-left text-sm text-danger hover:bg-subtle" onClick={() => onDelete(meeting)} type="button">Delete</button></div></details> }

export function StatusBadge({ status }: { status: Meeting['status'] }) { const tone = status === 'live' ? 'success' : status === 'upcoming' ? 'info' : status === 'archived' ? 'default' : 'default'; return <Badge tone={tone}>{status === 'live' ? 'Live' : status.charAt(0).toUpperCase() + status.slice(1)}</Badge> }
export function AiBadge({ status }: { status: NonNullable<Meeting['aiStatus']> }) { const isAi = status === 'AI Summary Available'; return <Badge tone={isAi ? 'ai' : status === 'Processing' ? 'info' : 'default'}><Sparkles size={12} />{status === 'AI Summary Available' ? 'AI Summary' : status}</Badge> }
