import { Grid2X2, List, Search, SlidersHorizontal } from 'lucide-react'

export type MeetingFilter = 'all' | 'upcoming' | 'live' | 'completed' | 'archived' | 'today' | 'week' | 'month'
export type MeetingSort = 'newest' | 'oldest' | 'longest' | 'shortest' | 'alphabetical'
export type MeetingView = 'grid' | 'list'

interface MeetingFiltersProps { filter: MeetingFilter; onFilterChange: (value: MeetingFilter) => void; onSearchChange: (value: string) => void; onSortChange: (value: MeetingSort) => void; onViewChange: (value: MeetingView) => void; search: string; sort: MeetingSort; view: MeetingView }

export function MeetingFilters({ filter, onFilterChange, onSearchChange, onSortChange, onViewChange, search, sort, view }: MeetingFiltersProps) {
  return <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><label className="relative block min-w-0 flex-1 lg:max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" size={17} /><input aria-label="Search meetings" className="h-10 w-full rounded-md border border-border bg-card pl-9 pr-3 text-sm text-foreground outline-none placeholder:text-muted focus:border-accent" onChange={(event) => onSearchChange(event.target.value)} placeholder="Search meetings..." value={search} /></label><div className="flex flex-wrap items-center gap-2"><label className="inline-flex h-10 items-center gap-2 rounded-md border border-border bg-card px-3 text-sm text-secondary"><SlidersHorizontal size={16} /><span className="sr-only">Filter meetings</span><select aria-label="Filter meetings" className="bg-transparent outline-none" onChange={(event) => onFilterChange(event.target.value as MeetingFilter)} value={filter}><option value="all">All</option><option value="upcoming">Upcoming</option><option value="live">Live</option><option value="completed">Completed</option><option value="archived">Archived</option><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option></select></label><label className="inline-flex h-10 items-center rounded-md border border-border bg-card px-3 text-sm text-secondary"><span className="sr-only">Sort meetings</span><select aria-label="Sort meetings" className="bg-transparent outline-none" onChange={(event) => onSortChange(event.target.value as MeetingSort)} value={sort}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="longest">Longest</option><option value="shortest">Shortest</option><option value="alphabetical">Alphabetical</option></select></label><div aria-label="View options" className="flex rounded-md border border-border bg-card p-0.5"><button aria-label="Grid view" aria-pressed={view === 'grid'} className={`rounded-sm p-2 ${view === 'grid' ? 'bg-subtle text-accent' : 'text-muted hover:text-foreground'}`} onClick={() => onViewChange('grid')} type="button"><Grid2X2 size={16} /></button><button aria-label="List view" aria-pressed={view === 'list'} className={`rounded-sm p-2 ${view === 'list' ? 'bg-subtle text-accent' : 'text-muted hover:text-foreground'}`} onClick={() => onViewChange('list')} type="button"><List size={16} /></button></div></div></div>
}
